# Generated by Django 5.2.7 on 2025-11-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.ticket'),
        ),
    ]
