# Generated by Django 5.2.7 on 2025-11-04 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_cart_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='seat_type',
            field=models.CharField(choices=[('Front', 'Front'), ('Behind Goal', 'Behind Goal'), ('Home Side', 'Home Side'), ('Away Side', 'Away Side')], default='Front', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'event', 'seat_type')},
        ),
    ]
