# Generated by Django 5.2.7 on 2025-11-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_cart_seat_type_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_type',
            field=models.CharField(choices=[('Front', 'Front'), ('Behind Goal', 'Behind Goal'), ('Home Side', 'Home Side'), ('Away Side', 'Away Side')], default='Front', max_length=20),
        ),
    ]
