# Generated by Django 5.2.7 on 2025-11-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_ticket_price_ticket_seat_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
