# Generated by Django 5.2.7 on 2025-11-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='background_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
