# Generated by Django 5.2.7 on 2025-11-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_ticket_seat_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
    ]
