# Generated by Django 5.2.7 on 2025-11-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_resell',
            field=models.BooleanField(default=False),
        ),
    ]
